In [354]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [356]:
ar1=np.arange(4)
ar1

array([0, 1, 2, 3])

In [358]:
ar1=np.arange(4).reshape(2,2)

In [360]:
ar1

array([[0, 1],
       [2, 3]])

In [6]:
list1=[1,2,3,4]

In [7]:
a=np.array(list1)

In [9]:
a

array([1, 2, 3, 4])

In [305]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [219]:
print(b.shape)

(2, 3)


In [147]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
lst=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [17]:
arr=np.array(lst)

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a=arr[0:,2:]
a

array([[3],
       [6],
       [9]])

In [24]:
a=arr[0:2,0:2]
print(a)

[[1 2]
 [4 5]]


In [26]:
a=arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [88]:
bool_array=np.array([
    [False,True,False],
    [True,False,True],
    [False,True,False]
])

In [100]:
n=arr[bool_array];
print(n)

[2 4 6 8]


In [134]:
a=np.array(lst)
bool_indexing=(a%2==0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [140]:
print(a[bool_indexing])
n=a[a%2==0]

[2 4 6 8]


In [310]:
c=a+b
c=np.add(a,b)
c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [311]:
c=a-b
c=np.subtract(a,b)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [312]:
c=a*b
c=np.multiply(a,b)
print(c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [361]:
c=a/b
c=np.divide(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [362]:
ar1=np.arange(4)
ar1

array([0, 1, 2, 3])

In [364]:
ar1=np.arange(4).reshape(2,2)

In [366]:
ar1

array([[0, 1],
       [2, 3]])

In [369]:
 np.concatenate([ar1,ar1],axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [372]:
df1=DataFrame({
    'A':[1,2,3],
    'B':[4,5,6]
})

In [374]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [415]:
df2=DataFrame({
    'A':[10,11],
    'B':[40,50]
})
df2

A   B
0  10  40
1  11  50

In [416]:
df3=DataFrame({
    'A':[40,50,60],
    'B':[70,80,90],
    'C':[10,11,12]
})
df3

A   B   C
0  40  70  10
1  50  80  11
2  60  90  12

In [417]:
pd.concat([df1,df2],axis=1)

A  B     A     B
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [418]:
pd.concat([df1,df2],axis=1,join='inner')

A  B   A   B
0  1  4  10  40
1  2  5  11  50

In [419]:
pd.concat([df1,df2],axis=1,join='inner',keys=['df1',"df2"])

df1    df2    
    A  B   A   B
0   1  4  10  40
1   2  5  11  50

In [422]:
df2= DataFrame({'A':'a','b','c','d','D':'e','f','g','h','E':'i','j','k','l'})

SyntaxError: invalid syntax (<ipython-input-422-4cdadbfd8874>, line 1)