In [23]:
import numpy as np
import pandas as pd

In [24]:
np.__version__

'1.16.5'

In [25]:
a=[1,2,3,4,5]

In [26]:
a

[1, 2, 3, 4, 5]

In [10]:
len(a)

5

In [28]:
array=np.array(a)

In [30]:
array

array([1, 2, 3, 4, 5])

In [32]:
array.size

5

In [62]:
pd.DataFrame(a,index='a','b','c','d','e')

SyntaxError: positional argument follows keyword argument (<ipython-input-62-d56879f55a0f>, line 1)

In [37]:
a1=np.arange(4)
a1

array([0, 1, 2, 3])

In [41]:
a2=np.zeros((4,4))
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
a3=np.ones((4,4))
a3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
a4=np.full((2,3),5)
a4

array([[5, 5, 5],
       [5, 5, 5]])

In [94]:
a5=np.random.normal(0,1,(3,3))
a5

array([[-1.88968094, -0.28038594, -0.17754295],
       [ 0.41184265,  0.02153343,  1.32751841],
       [-0.09562102,  0.53441802,  1.00620602]])

In [103]:
import matplotlib.pyplotp as plt

ModuleNotFoundError: No module named 'matplotlib.pyplotp'

In [142]:
b1=np.array([1,2,3])
b2=np.array([4,5,6])
b3=np.concatenate([b1,b2])

In [147]:
b3

array([1, 2, 3, 4, 5, 6])

In [150]:
c1=np.array([1,2,3,4])
c2=c1.reshape([2,2])
print(c2)

[[1 2]
 [3 4]]


In [153]:
d1=np.arange(4).reshape(1,4)
d1

array([[0, 1, 2, 3]])

In [156]:
d2=np.arange(2,10).reshape(2,4)
d2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [159]:
d3=np.concatenate([d1,d2])
d3

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [212]:
gop=a*10
print(gop)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [225]:
a1=np.arange(4).reshape(1,4)
a1

array([[0, 1, 2, 3]])

In [226]:
a2=np.arange(3,11).reshape(2,4)
a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [227]:
a3=np.concatenate([a1,a2],axis=0)
a3

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [230]:
a4=np.arange(3).reshape(3,1)
a4

array([[0],
       [1],
       [2]])

In [231]:
a5=a3+a4
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

In [233]:
a5=a3+a4

In [234]:
a6=a5<6
a6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [236]:
a6=np.arange(16).reshape(4,4)
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [186]:
data=[1,2,3,4,5,6,6,7]
k=np.array(data)
k.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7]])